GET http://localhost:3000/items


###
POST http://localhost:3000/items
Content-Type: application/json


{
    "name": "G PRO Wireless",
    "price": 120.99,
    "description": "Ultimate gaming mouse. Ultralow-latency LIGHTSPEED wireless."
} 

###

GET https://localhost:3000/items/6387563fe1b45d67815d926e


###

DELETE https://localhost:3000/items/6387563fe1b45d67815d926e