GET http://localhost:3000/items


###
POST http://localhost:3000/items
Content-Type: application/json


{
    "name": "G PRO Wireless",
    "price": 50.99,
    "description": "Ultimate gaming mouse. Ultralow-latency LIGHTSPEED wireless."
}

